source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YHLWebViewController_Example', :exclusive => true do
  pod 'YHLWebViewController', :path => '../'
end

target 'YHLWebViewController_Tests', :exclusive => true do
  pod 'YHLWebViewController', :path => '../'
end
